project:
  title: "Command Line Bootcamp Guides"
  output-dir: ./rendered/
  # lib-dir: ./static/
  # resources: 
    

format:
  html:
    highlight: github-dark
    css: ./markdown/style.css
    code-overflow: wrap
    code-block-bg: '#000000'
    highlight-style: arrow-dark
    link-external-icon: true
    link-external-newwindow: true
    # link-external-filter: '^(http|https)://'
    #'^(?:http:|https:)\/\/pigrenok\.github\.io\/command-line-bootcamp'


